# Generated by Django 6.0.3 on 2026-04-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('option1', models.CharField(max_length=100, verbose_name='Вариант 1')),
                ('option2', models.CharField(max_length=100, verbose_name='Вариант 2')),
                ('correct', models.CharField(max_length=100, verbose_name='Правильный ответ')),
            ],
        ),
    ]
